### ISSUE TITLE
Add/Modify ISSUE_TEMPLATE/config.yml across repositories. 

### ISSUE THREAD

**Issue by chicken-biryani** [moja-global/About_moja_global#169]
Every repository has:
`/.github/ISSUE_TEMPLATE/`. There are two possibilities that either `ISSUE_TEMPLATE` has `config.yml` or it doesn't.

**To do:**
1) If ISSUE_TEMPLATE doesn't have `config.yml` then add it else skip to 2.
2) Modify or add the following to 'config.yml':

```
blank_issues_enabled: true
contact_links:
  - name: moja global's Slack.
    url: https://join.slack.com/t/mojaglobal/shared_invite/zt-o6ta1ug0-rVLjAo460~d7JbZ~HpFFtw
    about: Talk to us about moja global and ask general questions.
  - name: moja global documentation
    url: https://docs.moja.global/en/latest/
    about:  The complete moja global documentation.
 - name: moja global's community website
    url: https://community.moja.global/
    about: Learn about moja global's projects and the community.
```
